// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSMImG4jG7GWFn-439OrdG6DWDEChyi0c',
    appId: '1:807511785838:android:de4d89dbd5fbe3d056417f',
    messagingSenderId: '807511785838',
    projectId: 'back-e44fb',
    storageBucket: 'back-e44fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc1jVDFWpDVrTleO3eSBWaFoUlW_AR-t0',
    appId: '1:807511785838:ios:df9a82ff207a559256417f',
    messagingSenderId: '807511785838',
    projectId: 'back-e44fb',
    storageBucket: 'back-e44fb.firebasestorage.app',
    androidClientId: '807511785838-3m3ps8v23jbsibt27dpfrf5c60vroas2.apps.googleusercontent.com',
    iosClientId: '807511785838-r99r4bc1200f89bedrh658kbebekj3gi.apps.googleusercontent.com',
    iosBundleId: 'com.example.ui',
  );

}